import "./static/styles/styles.scss";
console.log("setup project");

/**
 * TODO
 * 2 PAGINAS? 1 PAGINA E MODAL
 * MODAL
 * -FORMULARIO: NOME, CPF, TELEFONE, EMAIL
 * --ESTILO CONFORME DEFINIDO(INPUT E BOTOES)
 * --VALIDAÇOES E MASCARAS
 * --UTILIZAR O MESMO PARA CADASTRO E PARA EDIÇÃO
 *
 * LISTA
 * -CRIAR LISTAR E EXCLUIR CADASTROS
 * -PERSISTENCIA INDEXEDDB
 * -DADOS INICIAIS: https://private-21e8de-rafaellucio.apiary-mock.com/users
 * -A PARTIR DAI UTILIZAR INDEXEDDB
 *
 *
 * REQ:
 * -TESTES UNITARIOS
 * -BOAS PRATICAS DE OO
 * -INSTRUÇOES NO REDME
 * -DESCRIÇÃO DE COMO FOI FEITO
 * PLUS:
 * -RESPONSIVIDADE
 * -PERMITIR EDIÇÃO
 * -PRE PROCESSADOR CSS
 * -TESTE E2E
 * -PWA
 * -DARK MODE
 *
 *
 */
